# Generated by Django 3.1.4 on 2020-12-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201228_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodelname',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='mymodelname',
            old_name='my_field_name',
            new_name='title',
        ),
    ]
