# Generated by Django 3.1.4 on 2020-12-29 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20201228_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelname',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mymodelname',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
